name: rust

on:
  push:
    branches: [master, staging, trying]
  pull_request:
    branches: [master]

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  CI: 1
  RUSTFLAGS: "-W rust-2021-compatibility -D warnings"
  RUST_BACKTRACE: short

jobs:
  check-format:
    # Skip draft release PRs
    # if: github.actor_id != '166155226' || github.event_name != 'pull_request' || github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: rustfmt
      - name: Check format
        run: cargo fmt --all --check

  build:
    # Skip draft release PRs
    # if: github.actor_id != '166155226' || github.event_name != 'pull_request' || github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@1.78.0
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --workspace --all-features
      - name: Build tests
        run: cargo test --workspace --all-features --no-run
      - name: Run tests
        run: cargo test --workspace --all-features
      - name: Run clippy
        run: cargo clippy --all --all-features
